### ISSUE TITLE
Command Line on OS X 10.6.4

### ISSUE THREAD

**Issue by uho** [wavedrom/wavedrom.github.io#7] opened 2015-05-27 20:38 UTC
Launching Wavedrom like

```bash-3.2$ ./WaveDromEditor.app/Contents/MacOS/nwjs  source wavedrom-test.json png wavedrom.png```

results in the following error but no PNG output file:

```[58469:0527/222559:ERROR:nw_shell.cc(335)] ReferenceError: pngdata is not defined
    at nodeWebkit (file:///Users/uho/WaveDromEditor.app/Contents/Resources/app.nw/init.js:57:27)
    at file:///Users/uho/WaveDromEditor.app/Contents/Resources/app.nw/init.js:74:5
    at file:///Users/uho/WaveDromEditor.app/Contents/Resources/app.nw/init.js:104:3
[58469:0527/222559:INFO:CONSOLE(57)] "Uncaught ReferenceError: pngdata is not defined", source: file:///Users/uho/WaveDromEditor.app/Contents/Resources/app.nw/init.js (57)
[58477:0527/222607:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)```

Any suggestions?

Regards, Ulrich

**Comment by drom** [comment] 2015-06-01 07:39
could you try with v0.11.2?

**Comment by drom** [comment] 2015-06-03 04:23
Please try v0.11.4

**Comment by drom** [comment] 2015-06-03 14:28
duplicate of #6

**Comment by pepijnve** [comment] 2016-01-13 09:11
@drom I'm still seeing this issue with version 1.2.0 running on OS X 10.11.2. No matter what I try the `App.argv` and `App.fullargv` are always empty Array objects in `init.js`. See https://github.com/asciidoctor/asciidoctor-diagram/issues/89 for context.

**Comment by drom** [comment] 2016-01-13 15:43
@pepijnve it should work like:
```sh
./WaveDromEditor.app/Contents/MacOS/nwjs source <wavedrom-test.json> png <wavedrom.png>
```
frankly, I need to find machine to test it properly :(

**Comment by pepijnve** [comment] 2016-01-13 16:10
Proved to be a non-issue. Apologies for the confusion.

Travis CI provides [OS X environments](https://docs.travis-ci.com/user/osx-ci-environment/) these days that you could use for automated testing.

**Closed** 2016-02-05 16:32 UTC
Labels: bug, duplicate
